name: Flutter CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.3'
          channel: 'stable'
          cache: true
          
      - name: Install dependencies
        run: flutter pub get

      - name: Generate L10n
        run: flutter gen-l10n

      - name: update the version number
        run: dart update_build_number.dart

      - name: Build web
        run: flutter build web --release

      - name: Build APK
        run: flutter build apk

      - name: Setup Firebase CLI
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_PATH: ./build/web

#      - name: Upload APK
#        uses: actions/upload-artifact@v3
#        with:
#          name: release-apk
#          path: build/app/outputs/flutter-apk/app-release.apk 